### ISSUE TITLE
reportng revival?

### ISSUE THREAD

**Issue by juherr** [testng-team/reportng#1]
reportng is an important stone of the TestNG ecosystem and it is used by many people even if it is not maintained since years.

Some forks are still alive and continue to progress but they don't have the visibility they deserve.

That's why the @testng-team/testng proposes to own its own fork under the `org.testng` groupId on maven central if one or more person(s) want to take the leadership of the project.

@mingyu0519 @ptsiakos77 @AngryTester @guoxn @lenxeon @zhangyy-k @tm93112 @leopold-liu All of you have at least one recent (in the last year) commit. Are you interested in the idea?

**Comment by email2vimalraj** [comment]
@juherr and @krmahadevan: I'm working on it and will send the PR once done.

**Comment by juherr** [comment]
:+1:

**Comment by email2vimalraj** [comment]
@juherr and @krmahadevan : Can this issue be closed?

**Comment by krmahadevan** [comment]
Closed by https://github.com/testng-team/reportng/pull/2
