### ISSUE TITLE
Fix snapshot deployment

### ISSUE THREAD

**Issue by juherr** [testng-team/reportng#3]
Check https://travis-ci.com/testng-team/reportng/jobs/132740847

**Comment by juherr** [comment]
Ping @email2vimalraj

**Comment by krmahadevan** [comment]
@cbeust

Can you please create the below environment variables in
https://travis-ci.com/testng-team/reportng/settings

1. SONATYPE_USER
2. SONATYPE_PASSWORD

and include your credentials so that we can start publishing this library
into Maven Central under org.testng namespace ?

**Comment by juherr** [comment]
Fyi, I updated the travis file in order to activate sonarcloud.

But it should be only run on jdk8, like the deploy which is not yet the case.

**Comment by juherr** [comment]
And I think we should continue the version from last reportng version (1.1.4).
So maybe 1.1.5, 1.2 or 2.0 depending on what you expect to change :)

**Comment by krmahadevan** [comment]
@juherr - I think we can go with `1.2` (to signify that this artifact is now being published via a different group id and also has undergone some internal changes such as moving to maven and moving away from velocity template)

**Comment by email2vimalraj** [comment]
@juherr 

> But it should be only run on jdk8, like the deploy which is not yet the case.

Do you mean we have to remove the `jdk9` from the travis build config and support only `jdk8`?

**Comment by juherr** [comment]
No, jdk9 is a good way to check if it works (continuous integration) but only the target jvm must publish the artifact. Otherwise you don't know which one made the jar.
